CREATE TABLE [cp].[PrdIlKwang] (
    [Id]                     INT             IDENTITY (1, 1) NOT NULL,
    [IdTipoReporte]          INT             NULL,
    [IdUsuarios]             NVARCHAR (MAX)  NOT NULL,
    [IdMaquina]              INT             NOT NULL,
    [HoraInicio]             TIME (7)        NOT NULL,
    [HoraFin]                TIME (7)        NOT NULL,
    [Fecha]                  DATE            NOT NULL,
    [TiempoParo]             DECIMAL (10, 1) NULL,
    [IdArticulo]             NVARCHAR (MAX)  NOT NULL,
    [IdTipoFabricacion]      INT             NOT NULL,
    [Cliente]                NVARCHAR (500)  NOT NULL,
    [NumeroPedido]           INT             NULL,
    [VelocidadMaquina]       DECIMAL (10, 2) NOT NULL,
    [IdUbicacionBobinaA]     INT             NOT NULL,
    [IdAnchoBobinaA]         INT             NOT NULL,
    [FabricanteBobinaA]      NVARCHAR (200)  NOT NULL,
    [CodigoBobinaA]          NVARCHAR (200)  NOT NULL,
    [CalibreMmA]             DECIMAL (10, 2) NOT NULL,
    [IdColorBobinaA]         INT             NOT NULL,
    [AnchoMmA]               INT             NOT NULL,
    [PesoInicialKgA]         INT             NOT NULL,
    [PesoFinalKgA]           INT             NOT NULL,
    [MetrosInicialA]         INT             NOT NULL,
    [MetrosFinalA]           INT             NOT NULL,
    [EspesorInicialCmA]      INT             NOT NULL,
    [EspesorFinalCmA]        INT             NOT NULL,
    [ConsumoBobinaKgA]       AS              (CONVERT([decimal](10,2),[PesoInicialKgA])-CONVERT([decimal](10,2),[PesoFinalKgA])) PERSISTED,
    [IdUbicacionBobinaB]     INT             NOT NULL,
    [IdAnchoBobinaB]         INT             NOT NULL,
    [FabricanteBobinaB]      NVARCHAR (200)  NOT NULL,
    [CodigoBobinaB]          NVARCHAR (200)  NOT NULL,
    [CalibreMmB]             DECIMAL (10, 2) NOT NULL,
    [IdColorBobinaB]         INT             NOT NULL,
    [AnchoMmB]               INT             NOT NULL,
    [PesoInicialKgB]         INT             NOT NULL,
    [PesoFinalKgB]           INT             NOT NULL,
    [MetrosInicialB]         INT             NOT NULL,
    [MetrosFinalB]           INT             NOT NULL,
    [EspesorInicialCmB]      INT             NOT NULL,
    [EspesorFinalCmB]        INT             NOT NULL,
    [ConsumoBobinaKgB]       AS              (CONVERT([decimal](10,2),[PesoInicialKgB])-CONVERT([decimal](10,2),[PesoFinalKgB])) PERSISTED,
    [MetroInicialPoliol]     INT             NULL,
    [PesoInicialA]           DECIMAL (10, 2) NOT NULL,
    [CantidadUtilizadaA]     DECIMAL (10, 2) NOT NULL,
    [PesoFinalA]             DECIMAL (10, 2) NOT NULL,
    [VelocidadSuperiorA]     DECIMAL (10, 1) NOT NULL,
    [VelocidadInferiorA]     DECIMAL (10, 1) NOT NULL,
    [LoteA]                  NVARCHAR (150)  NOT NULL,
    [VencimientoA]           DATE            NOT NULL,
    [MetroInicialIsocianato] INT             NULL,
    [PesoInicialB]           DECIMAL (10, 2) NOT NULL,
    [CantidadUtilizadaB]     DECIMAL (10, 2) NOT NULL,
    [PesoFinalB]             DECIMAL (10, 2) NOT NULL,
    [VelocidadSuperiorB]     DECIMAL (10, 1) NOT NULL,
    [VelocidadInferiorB]     DECIMAL (10, 1) NOT NULL,
    [LoteB]                  NVARCHAR (100)  NOT NULL,
    [VencimientoB]           DATE            NOT NULL,
    [TotalProduccion]        DECIMAL (10, 2) NULL,
    [MetrosConDefecto]       DECIMAL (10, 2) NULL,
    [MermaM]                 DECIMAL (10, 2) NULL,
    [MetrosAdicionales]      DECIMAL (10, 2) NULL,
    [PorcentajeMerma]        DECIMAL (10, 2) NULL,
    [PorcentajeDefecto]      DECIMAL (10, 2) NULL,
    [Observaciones]          NVARCHAR (4000) NULL,
    [CantidadArranques]      INT             NULL,
    [IdUsuarioCreacion]      NVARCHAR (450)  NOT NULL,
    [FechaCreacion]          DATETIME        NOT NULL,
    [IdUsuarioActualizacion] NVARCHAR (450)  NULL,
    [FechaActualizacion]     DATETIME        NULL,
    [AprobadoSupervisor]     BIT             NOT NULL,
    [AprobadoGerencia]       BIT             NOT NULL,
    [IdAprobadoSupervisor]   NVARCHAR (450)  NULL,
    [IdAprobadoGerencia]     NVARCHAR (450)  NULL,
    CONSTRAINT [PK__PrdIlKwa__3214EC07DFC0EC0E] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PrdIlKwang_AnchoBobina] FOREIGN KEY ([IdAnchoBobinaA]) REFERENCES [cp].[AnchoBobina] ([Id]),
    CONSTRAINT [FK_PrdIlKwang_Maquinas] FOREIGN KEY ([IdMaquina]) REFERENCES [cp].[Maquinas] ([Id]),
    CONSTRAINT [FK_PrdIlKwang_PrdIlKwang_anchoBobinaB] FOREIGN KEY ([IdAnchoBobinaB]) REFERENCES [cp].[AnchoBobina] ([Id]),
    CONSTRAINT [FK_PrdIlKwang_PrdIlKwang_coloresBobina] FOREIGN KEY ([IdColorBobinaA]) REFERENCES [cp].[ColoresBobinas] ([Id]),
    CONSTRAINT [FK_PrdIlKwang_PrdIlKwang_coloresBobinaB] FOREIGN KEY ([IdColorBobinaB]) REFERENCES [cp].[ColoresBobinas] ([Id]),
    CONSTRAINT [FK_PrdIlKwang_PrdIlKwang_tipoFabricacion] FOREIGN KEY ([IdTipoFabricacion]) REFERENCES [cp].[TipoFabricacion] ([Id]),
    CONSTRAINT [FK_PrdIlKwang_UbicacionBobina] FOREIGN KEY ([IdUbicacionBobinaA]) REFERENCES [cp].[UbicacionBobina] ([Id])
);

